#!/usr/bin/env node
'use strict';

const sedbot = require('./sedbot.js');
const dotenv = require('dotenv');
const path = require('path');

const DEFAULT_TOKEN = '[USE .env file for reading TOKEN]';
const DEFAULT_DUCKPERCENT = 10;
const DEFAULT_KICKTOKEN = '[USE .env file for reading KICKTOKEN]';
const DEFAULT_DUCKCHANNELS = undefined;
const DEFAULT_DUCKCHANNELS_NOEJECT = undefined;

const opt = require('node-getopt').create([
  [ 'h', 'help',            'Show this help' ],
  [ 't', 'token={token}',   'Token to use for bot auth (default: ' + DEFAULT_TOKEN + ')' ],
  [ 'k', 'kick={token}',   'Token to use for bot auth (default: ' + DEFAULT_KICKTOKEN + ')' ],
  [ 'd', 'duckpercent={integer}',   'Pecent of time ducks should be let loose (default: ' + DEFAULT_DUCKPERCENT + ')' ],
  [ 'c', 'duckchannels=[chan1,chan2]',   'Channels in which ducks will be let loose (default: ' + DEFAULT_DUCKCHANNELS + ')' ],
  [ 'n', 'noeject=[chan1,chan2]',   'Channels in which will not eject you for missing (default: ' + DEFAULT_DUCKCHANNELS_NOEJECT + ')' ],
]).bindHelp().parseSystem();
// load .env file
dotenv.config({ path: path.resolve(__dirname, '.env') });

new sedbot.Sedbot({
  token: opt.options.token || process.env.TOKEN || DEFAULT_TOKEN,
  duckpercent: opt.options.duckpercent || process.env.DUCKPERCENT || DEFAULT_DUCKPERCENT,
  kicktoken: opt.options.kicktoken || process.env.KICKTOKEN || DEFAULT_KICKTOKEN,
  duckchannels: opt.options.duckchannels || (process.env.DUCKCHANNELS) ? process.env.DUCKCHANNELS.split(',') : '' || DEFAULT_DUCKCHANNELS,
  noeject: opt.options.noeject || (process.env.DUCKCHANNELS_NOEJECT) ? process.env.DUCKCHANNELS_NOEJECT.split(',') : '' || DEFAULT_DUCKCHANNELS_NOEJECT,
}).listen();
